### ISSUE TITLE
data-default-class-0.1.0 is missing GHC.Generics support for GHC 7.4

### ISSUE THREAD

**Issue by hvr** [mauke/data-default#13]
This has the unfortunate effect of violating the PVP contract, as data-default-class-0.1.0 lacks Generics support for GHC 7.4 even though GHC 7.4 does support Generics and will result in hard to fix install-plan issues on Hackage if left un-addressed.

My recommendation is to quickly release data-default-class-0.1.0.1 providing Generics support for GHC 7.4. I can provide a PR if needed.

**EDIT: In any case I'll edit in a lower-bound on `base` to make sure `data-default-class-0.1.0` is not selected in combination with GHC 7.4**

**Comment by mauke** [comment]
How does this violate PVP? And how does that cause problems?

**Comment by hvr** [comment]
E.g. a package declares that it needs `data-default-class == 0.1.*` relying on the PVP contract to assume that `data-default-class-0.1` in fact provides the Generics API support. However, now it turns out that `data-default-class` violates its contract, and now we end up that every package depending on `data-default-class` using the Generics API needs to exclude GHC 7.4 artificially for no good reason.

**Comment by mauke** [comment]
What if you're using GHC 7.2? It sounds like you can't assume that `data-default-class-0.1` provides generics in general; you always have to take the compiler version into account.

**Comment by hvr** [comment]
GHC 7.2 didn't have Generics support, the PVP is about *observable* API discontinuities. You can't observe the lack of Generics if your compiler doesn't support Generics.

**Comment by mauke** [comment]
What's an API discontinuity?

> You can't observe the lack of Generics if your compiler doesn't support Generics.

Of course I can: I'll get an error message.

**Comment by hvr** [comment]
Sorry, I originally lacked an important part in the wording:

> You can't observe the lack of Generics-support **in the API** if your compiler doesn't support Generics.

What I mean by that is, that if your compiler didn't support Generics, then you weren't able to write Generics-based code in the first place. So couldn't observe the variability in the exposed API.

**Comment by mauke** [comment]
That assumes 1) you only have one compiler, and 2) you only compile code you wrote yourself.

Wouldn't it also mean that if one of your modules doesn't support Generics, then you weren't able to write Generics based code in the first place? I mean, no matter what's missing Generics support where, you'll get an error from the compiler anyway.

**Comment by hvr** [comment]
The whole point of the PVP is to free me from having to have N compilers, and rely on the version number to provide me the contract.  Why would I otherwise *need* the PVP?

Put differently, I tell `cabal` that via `other-extensions: DeriveGenerics` that my code needs Generics support, and I tell via `build-depends: data-default-class == 0.1.*` that I need a version of `data-default-class` that provides  Generics-support.

But your package now violates this for GHC 7.4

**Comment by mauke** [comment]
`data-default-class-0.1` only provides Generics support from GHC 7.6 onwards, so your list of prerequisites is incomplete in that example.

You can get the same effect by using Generics and not putting `other-extensions: DeriveGenerics` in your cabal file. Then someone trying to use your package on an older compiler will get errors during build.

**Comment by hvr** [comment]
> data-default-class-0.1 only provides Generics support from GHC 7.6 onwards, so your list of prerequisites is incomplete in that example.

It's only incomplete because `data-default-class` fails to adhere to the PVP contract. I'm having a hard time finding a way to explain this in a way to make you see that. :-( 

> You can get the same effect by using Generics and not putting `other-extensions: DeriveGenerics` in your cabal file. 

If you lie in your `.cabal` file by not declaring the *local* requirements, then `cabal` has no choice but to believe that lie and run into a compile failure. The PVP relies on every package providing a uniform API which is not a function of its transitive dependencies (in a way that becomes observable) by using appropriate version bounds. The PVP is a complex system which is easy to break if unnecessary shortcuts like these are taken.

**Comment by hvr** [comment]
I've implement the trivial fix, see #13. Now it's basically either apply that PR or drop support for GHC 7.4 altogether.

**Comment by mauke** [comment]
> It's only incomplete because data-default-class fails to adhere to the PVP contract. I'm having a hard time finding a way to explain this in a way to make you see that. :-(

From what I see in https://wiki.haskell.org/Package_versioning_policy, the PVP is about correctly incrementing version numbers after changing the code and nothing else. That's why I don't understand your objection.

Apart from that, it wouldn't surprise me if data-default didn't follow PVP because this report is the first time I've heard of it, and conforming to it was never a goal.

I'm probably going to keep ignoring it because "*A.B* is known as the *major* version number" is just wrong. In data-default, *A* is the major version number. (Why store a single number across two fields in the first place?)

**Comment by hvr** [comment]
@mauke You don't have to like the PVP, but if you upload to Hackage, you are expected to follow it; lots of tooling (including Stackage) and everyone else involved assumes you *do* follow the PVP if you upload to Hackage.

If you don't like the Haskell comunity's versioning convention, because you happen to prefer SemVer, then the proper course of action for you is to get the policy changed rather than sabotaging the Hackage ecosystem by uploading packages which deliberately ignore the guidelines. Just because we don't enforce this  doesn't mean that Hackage is a free-for-all storage area where everyone just follows whatever personal convention they like most.

**Comment by mauke** [comment]
> You don't have to like the PVP, but if you upload to Hackage, you are expected to follow it

I didn't know that. Since when? And where is this documented?

> If you don't like the Haskell comunity's versioning convention

You're not the Haskell community. Or if you are, then so am I, and my versioning convention is also the Haskell community's.

If you don't like this Haskell community's versioning convention, because you happen to prefer PVP, then the proper course of action for you is to convince me to change my opinion rather than opening vague *X violates Y contract!!* issues and accusing me of sabotage.

**Comment by trskop** [comment]
> > You don't have to like the PVP, but if you upload to Hackage, you are expected to follow it

> I didn't know that. Since when? And where is this documented?

It's directly on <https://hackage.haskell.org/>. Quoting it:

> Guidelines for Hackage Packages:
> * All packages should follow the [Package Versioning Policy (PVP)](https://wiki.haskell.org/Package_versioning_policy).
> * Packages cannot be deleted, so you should consider uploading new versions packages as a package candidate and testing before publishing it to the main index.

**Comment by mauke** [comment]
Oh. I was looking on https://hackage.haskell.org/upload. I didn't expect important information for authors to be hidden in the middle of the front page, somewhere under "this is how you use this web site" and the list of package contents.

Do you know how long that has been on there?

**Comment by trskop** [comment]
> Do you know how long that has been on there?

I'm not really sure, but I think that it has been on the front page since the new Hackage. I recall reading something like this on old Hackage too it just was hidden somewhere else.

**Comment by mauke** [comment]
I tried to install ghc-7.4.2 to test this patch, but the binary distribution fails with a libgmp error, and the source distribution fails to build in Cabal because `System.Time` cannot be found. :-(
