### ISSUE TITLE
Drop the instance for function

### ISSUE THREAD

**Issue by nikita-volkov** [mauke/data-default#15]
The current instance isn't very useful and it occupies the space for a whole universe of way more useful default morphism instances, e.g.:

``` haskell
instance Default (Int8 -> Int) where def = fromIntegral
instance Default (String -> Data.Text.Text) where def = Data.Text.pack
```

Basically, the whole ["conversion"](http://hackage.haskell.org/package/conversion) ecosystem could be encoded this way.

**Comment by SX91** [comment]
Yes. It could also be used for parametrised construction (factories?):
```haskell
data Parameter = P1 | P2
data MyDataType = First A B C | Second D E F

instance Default (Parameter -> MyDataType) where
    def P1 = First def def def
    def P2 = Second def def def
```

**Comment by mauke** [comment]
Done in 7583f01db45e6af0e8a45f469cdb4543d3407a69.
