### ISSUE TITLE
Add Default instance for Bool

### ISSUE THREAD

**Issue by ndmitchell** [mauke/data-default#18]
Currently it's missing. Should return False.

**Comment by cdsmith** [comment]
I just ran into this.  I appreciate that there's a lot of sentiment against using data-default in the first place, or against most of its instances.  Nevertheless, I see no rational argument at all for having instances for `Int`, `String` and even `a -> b`, but not `Bool`.  This seems like a clear oversight that should be corrected.

**Comment by mauke** [comment]
Done in 82afda87522fd05ddace8a6ccc3ea4e8917e57ea.
