### ISSUE TITLE
Add GDefault instance for (a :+: b)

### ISSUE THREAD

**Issue by poscat0x04** [mauke/data-default#21]
The usefulness of the Default class came from its ability to generically derive `Default` instances. I would argue that adding a `GDefault` instance for sum types (which selects the first constructor) would further boost its usefulness. Plus we lose nothing from adding this since right now we need to manually write Default instances for sum types anyways.

**Comment by mauke** [comment]
Done in 06c724f637bf759170ec2037db72369cdc8026da.
