### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by tarleb** [mauke/data-default#28]
Please add a changelog to make it easier for downstream libraries to identify possible issues when a new major version is released.

**Comment by mauke** [comment]
Changelogs are not a documented feature of hackage/cabal.

**Comment by tfausak** [comment]
If you include a `changelog.txt` (or anything that passes [`isChangeLogFile`](https://github.com/haskell/hackage-server/blob/5b0d3b059410360651fc706fc7051ec46d5a7970/src/Distribution/Server/Packages/ChangeLog.hs#L10)) in your `extra-doc-files`, it will be rendered on Hackage. For example: <https://hackage.haskell.org/package/witch-1.2.2.0/changelog>.

**Comment by mauke** [comment]
I don't like relying on undocumented features.

**Comment by tarleb** [comment]
Personally, I'd just be happy to have some kind of human-readable documentation somewhere in the source repository. Changelog files are a fairly standard way to provide this. (I think some GNU projects use "anti-news" files that describe how features vanish as one goes back in time; whatever floats their boat.) If Hackage picks it up then that's a nice plus, but I'm happy as long as there's *something*.

**Comment by tarleb** [comment]
Thank you, much appreciated.
