### ISSUE TITLE
Is Default (e -> r) necessary?

### ISSUE THREAD

**Issue by 2piix** [mauke/data-default#6]
Do you personally use the (e -> r) instance?  Do you know if anybody else does?  I'm trying to define:

```
data Preference = Preference 
  { userId :: UserId
  , max   :: Int
  }
```

Obviously, the UserId can't be defaulted (sensibly -- i.e., while respecting the app's semantics for a UserId), but it would be pretty nice to be able to define:

```
instance Default (UserId -> Preference) where
  def = \uid -> (Preference uid 1000)
```

**Comment by mauke** [comment]
Removed in 7583f01db45e6af0e8a45f469cdb4543d3407a69.
