### ISSUE TITLE
Merge packages data-default-class and data-default-instances-base

### ISSUE THREAD

**Issue by sol** [mauke/data-default#7]
I may be missing something, but as I see it the reason to split the original `data-default` into separate packages is to minimize dependencies.

As both `data-default-class` and `data-default-instances-base` only introduce the `base` dependency, we could merge the packages.

Keeping the separate packages has the downside that the instances in `data-default-instances-base` are orphan (which I generally considered undesirable).  Are there any upsides?

**Comment by mauke** [comment]
What would be the best way to merge them? Move all the code from `...-instances-base` into `...-class` and have `...-instances-base` depend on `...-class` (reexporting the instances)?

**Comment by lfairy** [comment]
@mauke That seems reasonable to me.
